### ISSUE TITLE
Adding Delegates

### ISSUE THREAD

**Issue by Jonesk6843** [TaylorBrown96/Ring_Wars#71]
Our instructors has required us to add Delegates to our project. The requirements are:

- [x] Initialize Object load upon start up
- [x] Mob interation _(Combat and Dialogue)_
- [x] Item, room, mob description, and display

**Comment by Jonesk6843** [comment]
Almost through with the mob interaction task.

**Comment by TaylorBrown96** [comment]
I'll work on the loading delegate Thursday and Friday and push my changes be Saturday.
